name: my_pos_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # --- ALL PACKAGES GO HERE ---
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  supabase_flutter: ^2.8.0
  provider: ^6.0.0
  flutter_blue_plus: ^1.34.0
  esc_pos_utils: ^1.1.0
  image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# --- FLUTTER SETTINGS GO HERE ---
flutter:
  uses-material-design: true
  assets:
    - assets/pos.png